export const PAGE_TITLES = {
    DASHBOARD: "Dashboard",
    ADMIN_CALL: "Counter Terminal",
    QUEUE_MANAGEMENT: "Queue Management",
    REPORTS: "Reports",
    SETTINGS: "Settings",
    ARCHIVE: "Ticket Archive",
    COUNTERS: "Counter Report",
    ISSUED_PROCESSED_BY_HOUR: "Hourly Report",
    SERVICE_PERFORMANCE: "Service Report",
    EMPLOYEE_PERFORMANCE: "Employee Report",
    SYSTEM_SETTINGS: "System Settings",
    REGISTRATION: "Registration Management",
    DEVICE_MAPPING: "Device Mapping Settings",
    AUDIT_LOGS: "Audit Logs",
    ROLES: "Role Management",
    PERMISSIONS: "Permission Management",
    EMPLOYEES: "Employee Management",
    ENROLL_MEMBERSHIP_LOGS: "Enrollment Player Logs",
    MANAGE_DEVICES: "Device Management",
    DEFAULT: "Queue Management System"
} as const;